### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by WilsonScott** [apivideo/api.video-rtmpdroid#1]
### Version

1.0.5

### Environment that reproduces the issue

1、start stream and worked fine

### Is it reproducible in the example application?

Yes

### Reproduction steps

disconnect network

### Expected result

stop stream 

### Actual result

device frozen

**Comment by ThibaultBee** [comment]
Hello,

`rtmpdroid` is just a wrapper around `rtmpdump/librtmp` for Android. If anyone wants to use it, they must dispatch the API call to an another thread (an IO thread for example).
The user of this library must provide the buffer he wants to send.

That being said, there is no actually nothing of start stream in this library, we only pass buffer to this library.

My guess is that your issue is not in the right project. Could you add information of what you are trying to achieve?

**Comment by WilsonScott** [comment]
Thanks for your replay, i get h264 raw data from scrcpy ,and i use the library to pack the data to rtmp package . As u said it may be the thread problem,it only occured on Redmi device ,i will try it later.

**Comment by ThibaultBee** [comment]
Stalled issue.
Please reopen if needed
